namespace: ecommerce-apps
api-gateway:
  image:
    repository: "637043415174.dkr.ecr.ap-south-2.amazonaws.com/api-gateway"
    tag: "0ae37e00d47e09800d952d50550b5131e5d9950d"
  replicaCount: 2
  service:
    port: 4000
frontend:
  image:
    repository: "637043415174.dkr.ecr.ap-south-2.amazonaws.com/frontend"
    tag: "latest"
  replicaCount: 2
  service:
    port: 80
user-service:
  image:
    repository: "637043415174.dkr.ecr.ap-south-2.amazonaws.com/user-service"
    tag: "0ae37e00d47e09800d952d50550b5131e5d9950d"
  replicaCount: 2
  service:
    port: 4001
product-service:
  image:
    repository: "637043415174.dkr.ecr.ap-south-2.amazonaws.com/product-service"
    tag: "0ae37e00d47e09800d952d50550b5131e5d9950d"
  replicaCount: 2
  service:
    port: 4003
cart-service:
  image:
    repository: "637043415174.dkr.ecr.ap-south-2.amazonaws.com/cart-service"
    tag: "latest"
  replicaCount: 2
  service:
    port: 4004
inventory-service:
  image:
    repository: "637043415174.dkr.ecr.ap-south-2.amazonaws.com/inventory-service"
    tag: "0ae37e00d47e09800d952d50550b5131e5d9950d"
  replicaCount: 2
  service:
    port: 4005
order-service:
  image:
    repository: "637043415174.dkr.ecr.ap-south-2.amazonaws.com/order-service"
    tag: "latest"
  replicaCount: 2
  service:
    port: 4006
payment-service:
  image:
    repository: "637043415174.dkr.ecr.ap-south-2.amazonaws.com/payment-service"
    tag: "latest"
  replicaCount: 2
  service:
    port: 4007
notification-service:
  image:
    repository: "637043415174.dkr.ecr.ap-south-2.amazonaws.com/notification-service"
    tag: "latest"
  replicaCount: 2
  service:
    port: 4008
review-service:
  image:
    repository: "637043415174.dkr.ecr.ap-south-2.amazonaws.com/review-service"
    tag: "latest"
  replicaCount: 2
  service:
    port: 4002
