apiVersion: v1

kind: Service
metadata:
  name: api-gateway
  namespace: {{.Values.namespace}}
  labels:
    app: api-gateway

spec:
  selector:
    app: api-gateway
    
  ports:
    - port: {{.Values.api-gateway.service.port}}

      targetPort: {{.Values.api-gateway.service.port}}

  type: ClusterIP