apiVersion: v1
kind: Service

{{- $svc := index .Values "cart-service" -}}

metadata:
  name: cart-service
  namespace: {{.Values.namespace}}
  labels:
    app: cart-service

spec:
  selector:
    app: cart-service

  ports:
    - port: {{ $svc.service.port }}

      targetPort: {{ $svc.service.port }}

  type: ClusterIP
