apiVersion: external-secrets.io/v1beta1

kind: ExternalSecret

metadata:
  name: ecommerce-app-secret
  namespace: {{ .Values.namespace }}

spec:
  refreshInterval: 1h

  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore

  target:
    name: ecommerce-app-secret
    creationPolicy: Owner

  data:
    - secretKey: DB_PASS

      remoteRef:
        key: "ecommerce-app-secrets-prod-2026"
        property: DB_PASS

    - secretKey: ADMIN_PASSWORD

      remoteRef:
        key: "ecommerce-app-secrets-prod-2026"
        property: ADMIN_PASSWORD

    - secretKey: DB_URL

      remoteRef:
        key: "ecommerce-app-secrets-prod-2026"
        property: DB_URL