apiVersion: v1

kind: Service
metadata:
  name: frontend-ec
  namespace: {{.Values.namespace}}
  labels:
    app: frontend-ec

spec:
  selector:
    app: frontend-ec

  ports:
    - port: {{.Values.frontend.service.port}}
      
      targetPort: {{.Values.frontend.service.port}}

  type: ClusterIP

  

  