{{- $svc := index .Values "frontend" -}}
apiVersion: v1
kind: Service

metadata:
  name: frontend-ec
  namespace: {{.Values.namespace}}
  labels:
    app: frontend-ec

spec:
  selector:
    app: frontend-ec

  ports:
    - port: {{ $svc.service.port }}
      targetPort: {{ $svc.service.port }}

  type: ClusterIP

  

  