{{- $svc := index .Values "inventory-service" -}}
apiVersion: apps/v1
kind: Deployment


metadata:
  name: inventory-service
  namespace: {{.Values.namespace}}
  labels:
    app: inventory-service

spec:
  replicas: {{ $svc.replicaCount }}
  selector:
    matchLabels:
      app: inventory-service

  template:
    metadata:
      labels:
        app: inventory-service

    spec:
      containers:
        - name: inventory-service
          image: "{{ $svc.image.repository }}:{{ $svc.image.tag }}"
          ports:
            - containerPort: {{ $svc.service.port }}

          env:
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: ecommerce-config
                  key: DB_HOST

            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: ecommerce-config
                  key: DB_PORT

            - name: DB_USER
              valueFrom:
                configMapKeyRef:
                  name: ecommerce-config
                  key: DB_USER

            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: ecommerce-config
                  key: DB_NAME

            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: ecommerce-app-secret
                  key: DB_PASS

          readinessProbe:
            httpGet:
              path: /health
              port: {{ $svc.service.port }}

            initialDelaySeconds: 10
            periodSeconds: 5

          livenessProbe:
            httpGet:
              path: /health
              port: {{ $svc.service.port }}

            initialDelaySeconds: 30
            periodSeconds: 10

          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"

            limits:
              memory: "256Mi"
              cpu: "200m"