{{- $svc := index .Values "notification-service" -}}
apiVersion: v1
kind: Service


metadata:
  name: notification-service
  namespace: {{.Values.namespace}}
  labels:
    app: notification-service

spec:
  selector:
    app: notification-service

  ports:
    - port: {{ $svc.service.port }}

      targetPort: {{ $svc.service.port }}

  type: ClusterIP
