apiVersion: apps/v1

kind: Deployment
metadata:
  name: order-service
  namespace: {{.Values.namespace}}
  labels:
    app: order-service

spec:
  replicas: {{.Values.order-service.replicaCount}}
  selector:
    matchLabels:
      app: order-service

  template:
    metadata:
      labels:
        app: order-service

    spec:
      containers:
        - name: order-service
          image: "{{.Values.order-service.image.repository}}:{{.Values.order-service.image.tag}}"
          ports:
            - containerPort: {{.Values.order-service.service.port}}

          env:
            - name: GATEWAY_URL
              valueFrom:
                configMapKeyRef:
                  name: ecommerce-config
                  key: GATEWAY_URL

            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: ecommerce-config
                  key: DB_HOST

            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: ecommerce-config
                  key: DB_PORT

            - name: DB_USER
              valueFrom:
                configMapKeyRef:
                  name: ecommerce-config
                  key: DB_USER

            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: ecommerce-config
                  key: DB_NAME

            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: ecommerce-app-secret
                  key: DB_PASS


          readinessProbe:
            httpGet:
              path: /health
              port: {{.Values.order-service.service.port}}

            initialDelaySeconds: 10
            periodSeconds: 5

          livenessProbe:
            httpGet:
              path: /health
              port: {{.Values.order-service.service.port}}

            initialDelaySeconds: 30
            periodSeconds: 10

          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"

            limits:
              memory: "256Mi"
              cpu: "200m"