apiVersion: v1
kind: Service

{{- $svc := index .Values "payment-service" -}}

metadata:
  name: payment-service
  namespace: {{.Values.namespace}}
  labels:
    app: payment-service

spec:
  selector:
    app: payment-service

  ports:
    - port: {{ $svc.service.port }}

      targetPort: {{ $svc.service.port }}

  type: ClusterIP
