apiVersion: v1

kind: Service
metadata:
  name: payment-service
  namespace: {{.Values.namespace}}
  labels:
    app: payment-service

spec:
  selector:
    app: payment-service

  ports:
    - port: {{.Values.payment-service.service.port}}

      targetPort: {{.Values.payment-service.service.port}}

  type: ClusterIP
