apiVersion: v1

kind: Service
metadata:
  name: product-service
  namespace: {{.Values.namespace}}
  labels:
    app: product-service

spec:
  selector:
    app: product-service

  ports:
    - port: {{.Values.product-service.service.port}}

      targetPort: {{.Values.product-service.service.port}}

  type: ClusterIP
