apiVersion: v1
kind: Service

{{- $svc := index .Values "product-service" -}}

metadata:
  name: product-service
  namespace: {{.Values.namespace}}
  labels:
    app: product-service

spec:
  selector:
    app: product-service

  ports:
    - port: {{ $svc.service.port }}

      targetPort: {{ $svc.service.port }}

  type: ClusterIP
