{{- $svc := index .Values "review-service" -}}
apiVersion: v1
kind: Service


metadata:
  name: review-service
  namespace: {{.Values.namespace}}
  labels:
    app: review-service

spec:
  selector:
    app: review-service

  ports:
    - port: {{ $svc.service.port }}

      targetPort: {{ $svc.service.port }}

  type: ClusterIP
