apiVersion: v1

kind: Service
metadata:
  name: review-service
  namespace: {{.Values.namespace}}
  labels:
    app: review-service

spec:
  selector:
    app: review-service

  ports:
    - port: {{.Values.review-service.service.port}}

      targetPort: {{.Values.review-service.service.port}}

  type: ClusterIP
