{{- $svc := index .Values "user-service" -}}
apiVersion: v1
kind: Service


metadata:
  name: user-service
  namespace: {{.Values.namespace}}
  labels:
    app: user-service

spec:
  selector:
    app: user-service

  ports:
    - port: {{ $svc.service.port }}

      targetPort: {{ $svc.service.port }}

  type: ClusterIP


  