apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ecommerce-microservices
  namespace: argocd

spec:
  project: default

  source:
    repoURL: https://github.com/Sourav356/ecommerce-microservices-application.git
    targetRevision: main
    path: k8s-helm/ecommerce-app
    helm:
      valueFiles:
        - values.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: ecommerce-apps

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=true