name: Order Service CI

on:
  push:
    branches: [ main ]
    paths:
      - 'order-service/**' # Triggers only when files inside the order-service folder change

    paths-ignore:
      - 'k8s-helm/**'

concurrency:
  group: gitops-manifest-updates
  cancel-in-progress: true # Keeps the queue clean



jobs:
  trigger-ci:
    uses: ./.github/workflows/reusable-ci.yaml
    with:
      service_name: 'order-service' # Matches your folder name exactly
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
