name: Review Service CI

on:
  push:
    branches: [ main ]
    paths:
      - 'review-service/**' # Triggers only when files inside the review-service folder change

concurrency:
  group: gitops-manifest-updates
  cancel-in-progress: false # Forces them to wait in queue instead of canceling each other

jobs:
  trigger-ci:
    uses: ./.github/workflows/reusable-ci.yaml
    with:
      service_name: 'review-service' # Matches your folder name exactly
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
